### ISSUE TITLE
Not compatible w/ libmongoc >=0.8

### ISSUE THREAD

**Issue by pilwon** [Lytol/Mongo.jl#19]
`Mongo.jl` is broken in `libmongoc` >=0.8 due to C library's API change. (ex: `mongo_create` renamed to `mongo_alloc`) Please check their [change log](https://github.com/mongodb/mongo-c-driver/blob/master/HISTORY.md).

**Comment by Lytol** [comment]
Fixed in f8edc821bdf07f7e0fcdbe136f2fc7a9a7f60496
